### PR TITLE
Don't use elements `dataset`

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Doesn't play well with IE<11

https://app.getsentry.com/nextftcom/ft-next-frontend/group/60535752/

### CODE REVIEW

**Comment by matthew-andrews** [comment]
is this not polyfillable?

**Comment by ironsidevsquincy** [comment]
Not according to http://polyfill.webservices.ft.com/v1/docs/features/#Element

**Comment by matthew-andrews** [comment]
Right you are: @ironsidevsquincy  https://github.com/Financial-Times/polyfill-service/issues/188

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
